name: news_app
description: "News app for AppMint."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^8.2.0
  go_router: ^16.1.0

  dio: ^5.9.0
  json_annotation: ^4.9.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3

  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.6.0
  json_serializable: ^6.10.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700

  assets:
    - assets/icons/search_icon.svg
    - assets/icons/favorite.svg
    - assets/icons/favorite_pressed.svg
    - assets/icons/news_list.svg
    - assets/icons/news_list_pressed.svg
    - assets/icons/back_arrow.svg
    - assets/icons/star.svg
    - assets/icons/star_pressed.svg
